# -*- coding: utf-8 -*-
"""CS471_Assignment5_ShaneDyrdahl_DaxTaraleskof.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SH6YRT3-PqiI3OOhH7Y51aad1WpqcJfP
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math

from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import GridSearchCV
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split
import sklearn.metrics as metrics

# Load data
training_data = pd.read_csv("training.csv", header=None, usecols=[19, 23], names=['Time', 'Current'])
test_data = pd.read_csv("test.csv", header=None, usecols=[0, 4], names=['Time', 'Current'])

training_data, test_data

training_data = training_data[training_data['Time'] <= 5.4]
test_data = test_data[test_data['Time'] <= 2.4]

import matplotlib.pyplot as plt

df = training_data
fault_start = 5.1
fault_end = 5.4
# Separate the data points
fault_data = df[(df['Time'] >= fault_start) & (df['Time'] <= fault_end)]
normal_data = df[(df['Time'] < fault_start) | (df['Time'] > fault_end)]

plt.figure(figsize=(40, 6))

# Plotting for column D
plt.scatter(normal_data['Time'], normal_data['Current'], c='blue', label='Normal Operation (D)', alpha=0.5)
plt.scatter(fault_data['Time'], fault_data['Current'], c='red', label='Fault (D)', alpha=0.5)


plt.title('Scatter Plot of Current Over Time')
plt.xlabel('Time (s)')
plt.ylabel('Values')
plt.legend()
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt

df = test_data
fault_start = 2.1
fault_end = 2.4
# Separate the data points
fault_data = df[(df['Time'] >= fault_start) & (df['Time'] <= fault_end)]
normal_data = df[(df['Time'] < fault_start) | (df['Time'] > fault_end)]

plt.figure(figsize=(40, 6))

# Plotting for column D
plt.scatter(normal_data['Time'], normal_data['Current'], c='blue', label='Normal Operation (D)', alpha=0.5)
plt.scatter(fault_data['Time'], fault_data['Current'], c='red', label='Fault (D)', alpha=0.5)


plt.title('Scatter Plot of Current Over Time')
plt.xlabel('Time (s)')
plt.ylabel('Values')
plt.legend()
plt.grid(True)
plt.show()

# Define segmenting and labeling function

def segment_labeling(data, window, overlap, time1, time2):

  # Define the number of data points per segment = window size

  #index determines the start of a window
  #in each step of segmenting loop
  index = 0

  #windolap incorporates overlaping percentage
  windolap = math.floor (window * overlap)

  # Create an empty DataFrame for storing the labels
  labels_df = pd.DataFrame(columns=['label'])

  time_series = []

  while (index + window) < len(data):
      # Extract a segment of data
      segment = data.iloc[index : (index+window)]

      # Labeling based on a given time (the oscillation time is given)
      if any((time1 <= t <= time2) for t in segment['Time']):
        label = 'oscillation'
      else:
        label = 'normal'

      time_series.append(segment['Current'])

      # Append the label to the labels DataFrame
      labels_df = pd.concat([labels_df, pd.DataFrame({'label': [label]})], ignore_index=True)

      #Shifting the index forward by stride = window - windolap
      index += window - windolap

  # return lables_df as a DataFrame
  return time_series, labels_df

window = 200
overlap = 0.75

train_X, train_y = segment_labeling(training_data, window, overlap, 5.1, 5.4)
test_X, test_y = segment_labeling(test_data, window, overlap, 2.1, 2.4)

# convert to arrays because of runtime errors
X_train = np.array(train_X)
y_train = train_y['label']
X_test = np.array(test_X)
y_test = test_y['label']

rf_model = RandomForestClassifier(class_weight='balanced', random_state=42)

# tuning
param_grid = {
    'n_estimators': [50, 100, 150],
    'max_depth': [None, 10, 20, 30],
    'min_samples_leaf': [1, 2, 4, 6, 8],
}

# gridsearch which spits out values to graph with return_train_score=true
# used 'recall_macro' because gridsearch didn't like 'recall'. Also read up that it is better for imbalance
grid_search = GridSearchCV(estimator=rf_model, param_grid=param_grid, cv=5, scoring='recall_macro', n_jobs=-1, return_train_score=True)

grid_search.fit(X_train, y_train)

# get the best_params and score, then print to see which were tuned to be the best based on 'recall_macro'
best_params = grid_search.best_params_
best_score = grid_search.best_score_

print("Best hyperparameters:", best_params)
print("Best cross-validated recall:", best_score)

# Plotting Hyperparameter Tuning Results for min_samples_leaf
results = pd.DataFrame(grid_search.cv_results_)
results['param_min_samples_leaf'] = results['param_min_samples_leaf'].astype(str)

# number of trees (n_estimators) plots (barely sensitive) to rf without SMOTE
mean_of_means_estimators_train = results.groupby('param_n_estimators')['mean_train_score'].mean()
mean_of_means_estimators_val = results.groupby('param_n_estimators')['mean_test_score'].mean()

plt.figure(figsize=(12, 8))
plt.plot(mean_of_means_estimators_train.index, mean_of_means_estimators_train, label='Mean Train Scores', marker='o')
plt.plot(mean_of_means_estimators_val.index, mean_of_means_estimators_val, label='Mean Validation Scores', marker='o')
plt.xlabel('Number of Trees (n_estimators)')
plt.ylabel('Mean Score')
plt.title('Number of Trees vs Mean Score')
plt.legend()
plt.show()

# max_depth plots (not sensitive) to rf without SMOTE
mean_of_means_max_depth_train = results.groupby('param_max_depth')['mean_train_score'].mean()
mean_of_means_max_depth_val = results.groupby('param_max_depth')['mean_test_score'].mean()

plt.figure(figsize=(12, 8))
plt.plot(mean_of_means_max_depth_train.index, mean_of_means_max_depth_train, label='Mean Train Scores', marker='o')
plt.plot(mean_of_means_max_depth_val.index, mean_of_means_max_depth_val, label='Mean Validation Scores', marker='o')
plt.xlabel('Max Depth')
plt.ylabel('Mean Score (Mean of Means)')
plt.title('Max Depth vs Mean Score')
plt.legend()
plt.show()

# min_samples_leaf plots (very sensitive) for rf without SMOTE
mean_of_means_leaf_train = results.groupby('param_min_samples_leaf')['mean_train_score'].mean()
mean_of_means_leaf_val = results.groupby('param_min_samples_leaf')['mean_test_score'].mean()

plt.figure(figsize=(12, 8))
plt.plot(mean_of_means_leaf_train.index, mean_of_means_leaf_train, label='Mean Train Scores', marker='o')
plt.plot(mean_of_means_leaf_val.index, mean_of_means_leaf_val, label='Mean Validation Scores', marker='o')
plt.xlabel('Min Samples Leaf')
plt.ylabel('Mean Score (Mean of Means)')
plt.title('Min Samples Leaf vs Mean Score')
plt.legend()
plt.show()

# Final Evaluation on Test Data using the Best Estimator
best_estimator = grid_search.best_estimator_
y_predicted_test = best_estimator.predict(X_test)

# Calculate and display classification report at the end
accuracy = accuracy_score(y_test, y_predicted_test)
report = classification_report(y_test, y_predicted_test)

print("\nFinal Accuracy on test data:", accuracy)
print("Final Classification Report:\n", report)

"""Train the models by applying SMOTE to the data."""

# using SMOTE to see if it has any effect on the data
smote = SMOTE(random_state=42)
X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)

# check the oversampling compared to before
print("After SMOTE, training set label distribution:\n", pd.Series(y_train_smote).value_counts())

rf_model_smote = RandomForestClassifier(class_weight='balanced', random_state=42)

# tuning
param_grid = {
    'n_estimators': [50, 100, 150],
    'max_depth': [None, 10, 20, 30],
    'min_samples_leaf': [1, 2, 4, 6, 8],
}

# gridsearch which spits out values to graph with return_train_score=true
grid_search_smote = GridSearchCV(estimator=rf_model_smote, param_grid=param_grid, cv=5, scoring='recall_macro', n_jobs=-1, return_train_score=True)

grid_search_smote.fit(X_train_smote, y_train_smote)

# results from SMOTE tuning
best_params_smote = grid_search_smote.best_params_
best_score_smote = grid_search_smote.best_score_

print("Best hyperparameters (with SMOTE):", best_params_smote)
print("Best cross-validated recall (with SMOTE):", best_score_smote)

# plot the SMOTE results
results_smote = pd.DataFrame(grid_search_smote.cv_results_)
results_smote['param_min_samples_leaf'] = results_smote['param_min_samples_leaf'].astype(str)

# number of trees (n_estimators) plots (barely sensitive) with SMOTE
mean_of_means_estimators_train = results_smote.groupby('param_n_estimators')['mean_train_score'].mean()
mean_of_means_estimators_val = results_smote.groupby('param_n_estimators')['mean_test_score'].mean()

plt.figure(figsize=(12, 8))
plt.plot(mean_of_means_estimators_train.index, mean_of_means_estimators_train, label='Mean Train Scores', marker='o')
plt.plot(mean_of_means_estimators_val.index, mean_of_means_estimators_val, label='Mean Validation Scores', marker='o')
plt.xlabel('Number of Trees (n_estimators)')
plt.ylabel('Mean Score')
plt.title('Number of Trees vs Mean Score')
plt.legend()
plt.show()

# max_depth plots (not sensitive to this hyperparameter) with SMOTE
mean_of_means_max_depth_train = results_smote.groupby('param_max_depth')['mean_train_score'].mean()
mean_of_means_max_depth_val = results_smote.groupby('param_max_depth')['mean_test_score'].mean()

plt.figure(figsize=(12, 8))
plt.plot(mean_of_means_max_depth_train.index, mean_of_means_max_depth_train, label='Mean Train Scores', marker='o')
plt.plot(mean_of_means_max_depth_val.index, mean_of_means_max_depth_val, label='Mean Validation Scores', marker='o')
plt.xlabel('Max Depth')
plt.ylabel('Mean Score (Mean of Means)')
plt.title('Max Depth vs Mean Score')
plt.legend()
plt.show()

# min_samples_leaf plots (very sensitive) with SMOTE
mean_of_means_leaf_train = results_smote.groupby('param_min_samples_leaf')['mean_train_score'].mean()
mean_of_means_leaf_val = results_smote.groupby('param_min_samples_leaf')['mean_test_score'].mean()

plt.figure(figsize=(12, 8))
plt.plot(mean_of_means_leaf_train.index, mean_of_means_leaf_train, label='Mean Train Scores', marker='o')
plt.plot(mean_of_means_leaf_val.index, mean_of_means_leaf_val, label='Mean Validation Scores', marker='o')
plt.xlabel('Min Samples Leaf')
plt.ylabel('Mean Score (Mean of Means)')
plt.title('Min Samples Leaf vs Mean Score')
plt.legend()
plt.show()

# best tuned model for SMOTE data
best_estimator_smote = grid_search_smote.best_estimator_
y_predicted_test_smote = best_estimator_smote.predict(X_test)

# accuracy and classification reports for SMOTE data
accuracy_smote = accuracy_score(y_test, y_predicted_test_smote)
report_smote = classification_report(y_test, y_predicted_test_smote)

print("\nFinal Accuracy on test data:", accuracy_smote)
print("Final Classification Report:\n", report_smote)

"""Try to train models by preprocessing the data differently.
Used imputing because we noticed the model was throwing errors due to nan values or values that didn't exist.
"""

# preprocessing, tried a few different approaches to see if they worked on the data at all.
# https://scikit-learn.org/1.5/modules/impute.html for missing values
imputer = SimpleImputer(strategy='median')
training_data_preprocessed = pd.DataFrame(imputer.fit_transform(training_data[['Current']]), columns=['Current'])
test_data_preprocessed = pd.DataFrame(imputer.transform(test_data[['Current']]), columns=['Current'])

# readd time key
training_data_preprocessed['Time'] = training_data['Time'].values
test_data_preprocessed['Time'] = test_data['Time'].values

# https://scikit-learn.org/dev/modules/generated/sklearn.preprocessing.StandardScaler.html
scaler = StandardScaler()
training_data_preprocessed['Current'] = scaler.fit_transform(training_data_preprocessed[['Current']])
test_data_preprocessed['Current'] = scaler.transform(test_data_preprocessed[['Current']])

# https://scikit-learn.org/dev/modules/preprocessing.html#polynomial-features
poly = PolynomialFeatures(degree=2, include_bias=False)
training_poly = poly.fit_transform(training_data_preprocessed[['Current']])
test_poly = poly.transform(test_data_preprocessed[['Current']])

# put the processed data into a data frame
training_data_preprocessed = pd.concat([training_data_preprocessed, pd.DataFrame(training_poly, columns=poly.get_feature_names_out(['Current']))], axis=1)
test_data_preprocessed = pd.concat([test_data_preprocessed, pd.DataFrame(test_poly, columns=poly.get_feature_names_out(['Current']))], axis=1)

train_X_preprocessed, train_y_preprocessed = segment_labeling(training_data_preprocessed, window, overlap, 5.1, 5.4)
test_X_preprocessed, test_y_preprocessed = segment_labeling(test_data_preprocessed, window, overlap, 2.1, 2.4)

# convert to arrays because of runtime errors
X_train_preprocessed = np.array(train_X_preprocessed)
y_train_preprocessed = train_y_preprocessed['label']
X_test_preprocessed = np.array(test_X_preprocessed)
y_test_preprocessed = test_y_preprocessed['label']

train_X_preproc, train_y_preproc = segment_labeling(training_data_preprocessed, window, overlap, 5.1, 5.4)
test_X_preproc, test_y_preproc = segment_labeling(test_data_preprocessed, window, overlap, 2.1, 2.4)



"""Try to model it using the preprocessed data"""

rf_model_preproc = RandomForestClassifier(class_weight='balanced', random_state=42)

# tuning
param_grid = {
    'n_estimators': [50, 100, 150],
    'max_depth': [None, 10, 20, 30],
    'min_samples_leaf': [1, 2, 4, 6, 8],
}

# gridsearch which spits out values to graph with return_train_score=true
grid_search_preproc = GridSearchCV(estimator=rf_model_preproc, param_grid=param_grid, cv=5, scoring='recall_macro', n_jobs=-1, return_train_score=True)

# Flatten the 3D arrays to 2D
X_train_preprocessed = X_train_preprocessed.reshape(X_train_preprocessed.shape[0], -1)
X_test_preprocessed = X_test_preprocessed.reshape(X_test_preprocessed.shape[0], -1)

# Now fit the model
grid_search_preproc.fit(X_train_preprocessed, y_train_preprocessed)

# results from SMOTE tuning
best_params_preproc = grid_search_preproc.best_params_
best_score_preproc = grid_search_preproc.best_score_

print("Best hyperparameters (with different processing):", best_params_preproc)
print("Best cross-validated recall (with different processing):", best_score_preproc)